repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^characters/.*\.(png|jpg|jpeg|gif|svg)$
      - id: end-of-file-fixer
        exclude: ^characters/.*\.(png|jpg|jpeg|gif|svg)$
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: \.bat$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: ["feat", "fix", "docs", "chore", "refactor", "test", "ci", "build", "perf", "style", "revert"]
