"""Frozen Pydantic v2 schemas for every cross-module data type.

Schemas in this package are the runtime mirror of ``docs/contracts.md`` §2–§7.
They are immutable and may only change through the contract-change procedure
documented in §11 of that file.
"""

from __future__ import annotations

from .app import (
    SCHEMA_VERSION,
    AppConfig,
    AppRuntimeConfig,
    AvatarConfig,
    CompanionConfig,
    DistributionConfig,
    HotkeysConfig,
    InteractionConfig,
    LanguageConfig,
    LLMBackendConfig,
    LLMConfig,
    LLMFallbackConfig,
    LLMRetryConfig,
    LLMRoleAssignments,
    MemoryConfig,
    OverlayConfig,
    PanelConfig,
    ResponsePresentationConfig,
    SecretReference,
    STTConfigSection,
    STTWakeConfig,
    TaskRuntimeConfigEntry,
    TasksConfig,
    ToolsConfig,
    TrayConfig,
    TTSCloneConfig,
    TTSConfigSection,
    UIConfig,
    VoiceConfig,
    VoiceModesConfig,
)
from .avatar import AvatarDirective, CharacterPack, Emotion, EmotionFrames, State
from .events import (
    AvatarCue,
    ComponentHealthChanged,
    ConfigUpdated,
    ConsentRequired,
    ConsentResolved,
    ErrorEvent,
    GestureDetected,
    HandPoseEnded,
    HandPoseStarted,
    LLMReplyComplete,
    LLMStarted,
    LLMTokenStreamed,
    MovementDetected,
    RuntimeEvent,
    RuntimeEventAdapter,
    RuntimeStateChanged,
    TaskCompleted,
    TaskSubmitted,
    TaskUpdatedEvent,
    TranscriptPreview,
    TTSChunkSpoken,
    TTSFailed,
    TTSFinished,
    TTSInterrupted,
    TTSQueued,
    TTSReady,
    TTSStarted,
    TurnStateChanged,
    UserSpeechFinal,
    UserSpeechStarted,
    UserTextSubmitted,
    WakeDetected,
)
from .llm import LLMChunk, LLMMessage, LLMUsage, ToolSpec
from .tasks import (
    Artifact,
    TaskConstraints,
    TaskError,
    TaskHandle,
    TaskInput,
    TaskRequest,
    TaskResult,
    TaskStatus,
    TaskStatusName,
    TaskUpdate,
)
from .vision import (
    BodyPose,
    GestureDetection,
    HandLandmark,
    HandPose,
    HeadPose,
    Landmark,
    MovementDetection,
    VisionClassifierConfig,
    VisionConfig,
    VisionDetectorConfig,
    VisionFrame,
)
from .voice import STTConfig, Transcript, TTSChunkBoundary, TTSConfig, WakeEvent

__all__ = [
    "SCHEMA_VERSION",
    # app
    "AppConfig",
    "AppRuntimeConfig",
    # tasks
    "Artifact",
    "AvatarConfig",
    "AvatarCue",
    # avatar
    "AvatarDirective",
    # vision
    "BodyPose",
    "CharacterPack",
    "CompanionConfig",
    "ComponentHealthChanged",
    # events
    "ConfigUpdated",
    "ConsentRequired",
    "ConsentResolved",
    "DistributionConfig",
    "Emotion",
    "EmotionFrames",
    "ErrorEvent",
    "GestureDetected",
    "GestureDetection",
    "HandLandmark",
    "HandPose",
    "HandPoseEnded",
    "HandPoseStarted",
    "HeadPose",
    "HotkeysConfig",
    "InteractionConfig",
    "LLMBackendConfig",
    # llm
    "LLMChunk",
    "LLMConfig",
    "LLMFallbackConfig",
    "LLMMessage",
    "LLMReplyComplete",
    "LLMRetryConfig",
    "LLMRoleAssignments",
    "LLMStarted",
    "LLMTokenStreamed",
    "LLMUsage",
    "Landmark",
    "LanguageConfig",
    "MemoryConfig",
    "MovementDetected",
    "MovementDetection",
    "OverlayConfig",
    "PanelConfig",
    "ResponsePresentationConfig",
    "RuntimeEvent",
    "RuntimeEventAdapter",
    "RuntimeStateChanged",
    # voice
    "STTConfig",
    "STTConfigSection",
    "STTWakeConfig",
    "SecretReference",
    "State",
    "TTSChunkBoundary",
    "TTSChunkSpoken",
    "TTSCloneConfig",
    "TTSConfig",
    "TTSConfigSection",
    "TTSFailed",
    "TTSFinished",
    "TTSInterrupted",
    "TTSQueued",
    "TTSReady",
    "TTSStarted",
    "TaskCompleted",
    "TaskConstraints",
    "TaskError",
    "TaskHandle",
    "TaskInput",
    "TaskRequest",
    "TaskResult",
    "TaskRuntimeConfigEntry",
    "TaskStatus",
    "TaskStatusName",
    "TaskSubmitted",
    "TaskUpdate",
    "TaskUpdatedEvent",
    "TasksConfig",
    "ToolSpec",
    "ToolsConfig",
    "Transcript",
    "TranscriptPreview",
    "TrayConfig",
    "TurnStateChanged",
    "UIConfig",
    "UserSpeechFinal",
    "UserSpeechStarted",
    "UserTextSubmitted",
    "VisionClassifierConfig",
    "VisionConfig",
    "VisionDetectorConfig",
    "VisionFrame",
    "VoiceConfig",
    "VoiceModesConfig",
    "WakeDetected",
    "WakeEvent",
]
