"""Frozen Pydantic v2 schemas for every cross-module data type.

Schemas in this package are the runtime mirror of ``docs/contracts.md`` §2–§7.
They are immutable and may only change through the contract-change procedure
documented in §11 of that file.
"""

from __future__ import annotations

from .app import (
    SCHEMA_VERSION,
    AppConfig,
    AppRuntimeConfig,
    AvatarConfig,
    HotkeysConfig,
    LLMConfig,
    LLMFallbackConfig,
    LLMRetryConfig,
    OverlayConfig,
    PanelConfig,
    STTConfigSection,
    STTWakeConfig,
    TaskRuntimeConfigEntry,
    TasksConfig,
    TrayConfig,
    TTSConfigSection,
    UIConfig,
    VoiceConfig,
    VoiceModesConfig,
)
from .avatar import AvatarDirective, CharacterPack, Emotion, EmotionFrames, State
from .events import (
    ConfigUpdated,
    ConsentRequired,
    ConsentResolved,
    ErrorEvent,
    GestureDetected,
    HandPoseEnded,
    HandPoseStarted,
    LLMReplyComplete,
    LLMStarted,
    LLMTokenStreamed,
    MovementDetected,
    RuntimeEvent,
    RuntimeEventAdapter,
    TaskCompleted,
    TaskSubmitted,
    TaskUpdatedEvent,
    TranscriptPreview,
    TTSChunkSpoken,
    TTSFinished,
    TTSInterrupted,
    TTSStarted,
    UserSpeechFinal,
    UserSpeechStarted,
    UserTextSubmitted,
    WakeDetected,
)
from .llm import LLMChunk, LLMMessage, LLMUsage, ToolSpec
from .tasks import (
    Artifact,
    TaskConstraints,
    TaskError,
    TaskHandle,
    TaskInput,
    TaskRequest,
    TaskResult,
    TaskStatus,
    TaskStatusName,
    TaskUpdate,
)
from .vision import (
    BodyPose,
    GestureDetection,
    HandLandmark,
    HandPose,
    HeadPose,
    Landmark,
    MovementDetection,
    VisionClassifierConfig,
    VisionConfig,
    VisionDetectorConfig,
    VisionFrame,
)
from .voice import STTConfig, Transcript, TTSChunkBoundary, TTSConfig, WakeEvent

__all__ = [
    "SCHEMA_VERSION",
    # app
    "AppConfig",
    "AppRuntimeConfig",
    # tasks
    "Artifact",
    "AvatarConfig",
    # avatar
    "AvatarDirective",
    # vision
    "BodyPose",
    "CharacterPack",
    # events
    "ConfigUpdated",
    "ConsentRequired",
    "ConsentResolved",
    "Emotion",
    "EmotionFrames",
    "ErrorEvent",
    "GestureDetected",
    "GestureDetection",
    "HandLandmark",
    "HandPose",
    "HandPoseEnded",
    "HandPoseStarted",
    "HeadPose",
    "HotkeysConfig",
    "Landmark",
    # llm
    "LLMChunk",
    "LLMConfig",
    "LLMFallbackConfig",
    "LLMMessage",
    "LLMReplyComplete",
    "LLMRetryConfig",
    "LLMStarted",
    "LLMTokenStreamed",
    "LLMUsage",
    "MovementDetected",
    "MovementDetection",
    "OverlayConfig",
    "PanelConfig",
    "RuntimeEvent",
    "RuntimeEventAdapter",
    # voice
    "STTConfig",
    "STTConfigSection",
    "STTWakeConfig",
    "State",
    "TTSChunkBoundary",
    "TTSChunkSpoken",
    "TTSConfig",
    "TTSConfigSection",
    "TTSFinished",
    "TTSInterrupted",
    "TTSStarted",
    "TaskCompleted",
    "TaskConstraints",
    "TaskError",
    "TaskHandle",
    "TaskInput",
    "TaskRequest",
    "TaskResult",
    "TaskRuntimeConfigEntry",
    "TaskStatus",
    "TaskStatusName",
    "TaskSubmitted",
    "TaskUpdate",
    "TaskUpdatedEvent",
    "TasksConfig",
    "ToolSpec",
    "Transcript",
    "TranscriptPreview",
    "TrayConfig",
    "UIConfig",
    "UserSpeechFinal",
    "UserSpeechStarted",
    "UserTextSubmitted",
    "VisionClassifierConfig",
    "VisionConfig",
    "VisionDetectorConfig",
    "VisionFrame",
    "VoiceConfig",
    "VoiceModesConfig",
    "WakeDetected",
    "WakeEvent",
]
