"""openmimicry-core: contracts, schemas, EventBus, runtime, config, logging.

The cross-module **shape** lives here in ``contracts`` and ``schemas`` and is
frozen by ``docs/contracts.md``. The cross-module **runtime services**
(``EventBus``, ``Runtime``, ``AppConfig`` loader, structlog setup) live as
sibling modules in this package and are owned by M0.
"""

from __future__ import annotations

# Concrete EventBus + Runtime + RuntimeStore (M0 implementation).
from .bus import EventBus

# Contracts — the Protocols every adapter satisfies.
from .contracts import (
    AvatarDirector,
    AvatarOrchestrator,
    AvatarRuntimeAdapter,
    BodyDetector,
    GestureClassifier,
    HandDetector,
    HeadDetector,
    LandmarkDetector,
    LLMAdapter,
    MovementClassifier,
    SpeechController,
    STTAdapter,
    TaskRuntimeAdapter,
    TTSAdapter,
    VisionAdapter,
    WakeController,
)
from .runtime import Runtime, create_runtime

# Schemas — the data shapes every module exchanges.
from .schemas import (
    SCHEMA_VERSION,
    AppConfig,
    Artifact,
    AvatarCue,
    AvatarDirective,
    BodyPose,
    CharacterPack,
    ComponentHealthChanged,
    ConfigUpdated,
    ConsentRequired,
    ConsentResolved,
    Emotion,
    EmotionFrames,
    ErrorEvent,
    GestureDetected,
    GestureDetection,
    HandLandmark,
    HandPose,
    HandPoseEnded,
    HandPoseStarted,
    HeadPose,
    Landmark,
    LLMChunk,
    LLMMessage,
    LLMReplyComplete,
    LLMStarted,
    LLMTokenStreamed,
    LLMUsage,
    MovementDetected,
    MovementDetection,
    RuntimeEvent,
    RuntimeEventAdapter,
    RuntimeStateChanged,
    State,
    STTConfig,
    TaskCompleted,
    TaskConstraints,
    TaskError,
    TaskHandle,
    TaskInput,
    TaskRequest,
    TaskResult,
    TaskStatus,
    TaskStatusName,
    TaskSubmitted,
    TaskUpdate,
    TaskUpdatedEvent,
    ToolSpec,
    Transcript,
    TranscriptPreview,
    TTSChunkBoundary,
    TTSChunkSpoken,
    TTSConfig,
    TTSFailed,
    TTSFinished,
    TTSInterrupted,
    TTSQueued,
    TTSReady,
    TTSStarted,
    TurnStateChanged,
    UserSpeechFinal,
    UserSpeechStarted,
    UserTextSubmitted,
    VisionClassifierConfig,
    VisionConfig,
    VisionDetectorConfig,
    VisionFrame,
    WakeDetected,
    WakeEvent,
)
from .store import RuntimeStore

__all__ = [
    "SCHEMA_VERSION",
    # Schema data types
    "AppConfig",
    "Artifact",
    "AvatarCue",
    "AvatarDirective",
    # Protocols
    "AvatarDirector",
    "AvatarOrchestrator",
    "AvatarRuntimeAdapter",
    "BodyDetector",
    "BodyPose",
    "CharacterPack",
    "ComponentHealthChanged",
    "ConfigUpdated",
    "ConsentRequired",
    "ConsentResolved",
    "Emotion",
    "EmotionFrames",
    "ErrorEvent",
    # Runtime classes
    "EventBus",
    "GestureClassifier",
    "GestureDetected",
    "GestureDetection",
    "HandDetector",
    "HandLandmark",
    "HandPose",
    "HandPoseEnded",
    "HandPoseStarted",
    "HeadDetector",
    "HeadPose",
    "LLMAdapter",
    "LLMChunk",
    "LLMMessage",
    "LLMReplyComplete",
    "LLMStarted",
    "LLMTokenStreamed",
    "LLMUsage",
    "Landmark",
    "LandmarkDetector",
    "MovementClassifier",
    "MovementDetected",
    "MovementDetection",
    "Runtime",
    "RuntimeEvent",
    "RuntimeEventAdapter",
    "RuntimeStateChanged",
    "RuntimeStore",
    "STTAdapter",
    "STTConfig",
    "SpeechController",
    "State",
    "TTSAdapter",
    "TTSChunkBoundary",
    "TTSChunkSpoken",
    "TTSConfig",
    "TTSFailed",
    "TTSFinished",
    "TTSInterrupted",
    "TTSQueued",
    "TTSReady",
    "TTSStarted",
    "TaskCompleted",
    "TaskConstraints",
    "TaskError",
    "TaskHandle",
    "TaskInput",
    "TaskRequest",
    "TaskResult",
    "TaskRuntimeAdapter",
    "TaskStatus",
    "TaskStatusName",
    "TaskSubmitted",
    "TaskUpdate",
    "TaskUpdatedEvent",
    "ToolSpec",
    "Transcript",
    "TranscriptPreview",
    "TurnStateChanged",
    "UserSpeechFinal",
    "UserSpeechStarted",
    "UserTextSubmitted",
    "VisionAdapter",
    "VisionClassifierConfig",
    "VisionConfig",
    "VisionDetectorConfig",
    "VisionFrame",
    "WakeController",
    "WakeDetected",
    "WakeEvent",
    "create_runtime",
]

__version__ = "1.8.5"
